name: Test
run-name: None
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        run: |
          cmake -H. -B_build
          cmake --build _build
          cmake --build _build --target test -- ARGS=--verbose
      - name: Generate and send a code coverage report to Coveralls
        uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: third-party
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}